# Generated by Django 4.1 on 2024-07-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
