# Generated by Django 4.1 on 2024-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_delete_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Share',
            new_name='Dues',
        ),
        migrations.RenameModel(
            old_name='Vouchers',
            new_name='Voucher',
        ),
        migrations.DeleteModel(
            name='Acrivity',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_number',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='duration',
            field=models.DurationField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
