# Generated by Django 4.1 on 2024-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_transactions_remove_plan_plan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age',
            field=models.CharField(default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
