# Generated by Django 5.0.7 on 2024-10-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_user_delete_mainuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(default='', max_length=100)),
                ('passsword', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
