# Generated by Django 4.1 on 2024-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_activity_age_activity_description'),
        ('back', '0007_mainuser_delete_user'),
    ]

    operations = [
    ]
