# Generated by Django 4.1 on 2024-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_merge_20241209_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
