# Generated by Django 5.0.7 on 2024-12-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_mainuser_options_alter_mainuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
            ],
        ),
    ]
