# Generated by Django 4.1 on 2025-01-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_mainuser_options_alter_mainuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='elaboration_date',
        ),
        migrations.AddField(
            model_name='routine',
            name='details',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
