# Generated by Django 4.1 on 2025-01-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_remove_routine_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='back.clients'),
        ),
        migrations.AddField(
            model_name='routine',
            name='day',
            field=models.CharField(default='Lunes', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(default='Rutina del dia', max_length=100),
        ),
        migrations.AlterField(
            model_name='routine',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
