# Generated by Django 5.0.7 on 2024-12-14 18:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_alter_mainuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='mainuser',
            old_name='name',
            new_name='username',
        ),
    ]
