# Generated by Django 5.0.7 on 2024-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_alter_mainuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
