# Generated by Django 5.0.7 on 2025-01-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_routine_client_routine_day_routine_name_and_more'),
        ('back', '0015_alter_mainuser_mail_alter_mainuser_username'),
    ]

    operations = [
    ]
