# Generated by Django 4.1 on 2025-01-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_merge_20250108_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='back.clients'),
        ),
    ]
